spring:
  datasource:
    url: jdbc:postgresql://language_db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
server:
  port: ${PORT}
argon2:
  salt-length: ${ARGON2_SALT_LENGTH}
  hash-length: ${ARGON2_HASH_LENGTH}
  parallelism: ${ARGON2_PARALLELISM}
  memory: ${ARGON2_MEMORY}
  iterations: ${ARGON2_ITERATIONS}
